language: minimal
python:
  - '3.6'

matrix:
  include:
  - dist: xenial
    addons:
      apt:
        sources:
        - sourceline: 'ppa:jonathonf/vim'
        packages:
        - vim
    install: |
      pip install cmake
    env:
    - VIM=vim
  - dist: xenial
    addons:
      apt:
        sources:
        - sourceline: 'ppa:neovim-ppa/stable'
        packages:
        - neovim
    install: |
      pip install cmake
    env:
    - VIM=nvim
  - os: osx
    addons:
      homebrew:
        packages:
        - vim
        - cmake
    env:
    - VIM=vim
  - os: osx
    addons:
      homebrew:
        packages:
        - neovim
        - cmake
    env:
    - VIM=nvim
  - os: windows
    install:
    - choco install vim
    - choco install cmake
    env:
    - VIM=vim
  - os: windows
    install:
    - choco install neovim
    - choco install cmake
    env:
    - VIM=nvim

after_install: |
  cmake --version

before_script: |
  git clone https://github.com/junegunn/vader.vim.git ~/.vim/plugged/vader.vim

script: $VIM -Nu tests/mini.vimrc -Esc 'Vader! tests/*'
