language: vim

matrix:
  include:
  - dist: xenial
    addons:
      apt:
        sources:
        - sourceline: 'ppa:jonathonf/vim'
        packages:
        - vim
  - os: macos
    addons:
      homebrew:
        packages:
        - vim

before_script: |
  git clone https://github.com/junegunn/vader.vim.git ~/.vim/plugged/vader.vim

script: ./scripts/run_tests.sh
