trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  ImageName: 'pleroux0/vim'
  ContainerName: 'vim'
  VimExe: 'vim'

steps:
- script: |
		docker pull $(ImageName)
  displayName: 'docker pull'
- script: |
		docker run -it -d --name $(ContainerName) $(ImageName)
  displayName: 'docker run'
- script: |
		docker exec $(ContainerName) cp . vim:~/MyCMake.vim
  displayName: 'Install MyCMake.vim'
- script: |
    git clone https://github.com/junegunn/vader.vim.git ~/vader.vim
		docker cp vader.vim $(ContainerName):~/.vim/plugged/vader.vim
  displayName: 'Install Vader.vim'
- script: |
		docker exec -w ~/MyCMake.vim $(ContainerName) ./scripts/run_tests.sh
	displayName: 'Run tests'
