trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  ImageName: 'pleroux0/vim'
  ContainerName: 'vim'
  VimExe: 'vim'

steps:
- script: docker pull $(ImageName)
  displayName: 'docker pull'
- script: docker run -it -d --name $(ContainerName) $(ImageName)
  displayName: 'docker run'
- script: docker cp . $(ContainerName):/root/MyCMake.vim
  displayName: 'Install MyCMake.vim'
- script: docker exec $(ContainerName) mkdir -p /root/.vim/plugged
  displayName: 'Setup plugin folder'
- script: git clone https://github.com/junegunn/vader.vim.git ~/vader.vim
  displayName: 'Clone Vader.vim'
- script: docker cp ~/vader.vim $(ContainerName):/root/.vim/plugged/vader.vim
  displayName: 'Install Vader.vim'
- script: docker exec $(ContainerName) apk add make cmake
  displayName: 'Install binary dependencies'
- script: docker exec -w /root/MyCMake.vim $(ContainerName) ./scripts/run_tests.sh
  displayName: 'Run tests'
